[[headers]]
  for = "/*"
  [headers.values]
  Content-Security-Policy = """
    default-src 'self';
    script-src 'self' 'unsafe-inline' 'unsafe-eval'
      https://www.googletagmanager.com
      https://www.google-analytics.com
      https://www.googleadservices.com
      https://www.gstatic.com
      https://www.google.com
      https://www.google.pl
      https://www.recaptcha.net
      https://www.youtube.com
      https://tagassistant.google.com
      https://pagead2.googlesyndication.com
      data:;
    img-src 'self' data:
      https://www.google-analytics.com
      https://pagead2.googlesyndication.com
      https://googleads.g.doubleclick.net
      https://www.google.com
      https://www.google.com/pagead/
      https://www.google.pl
      https://www.google.pl/pagead/
      https://googleads.g.doubleclick.net/pagead/viewthroughconversion/
      https://www.googletagmanager.com
      https://www.googleadservices.com
      https://fonts.gstatic.com
      https://www.gstatic.com;
    connect-src 'self'
      https://puknkvmgocmjgcgjynda.supabase.co
      https://www.google.com
      https://www.google.com/pagead/
      https://www.google.pl
      https://www.google.pl/pagead/
      https://googleads.g.doubleclick.net
      https://www.google-analytics.com
      https://www.googletagmanager.com
      https://www.googleadservices.com
      https://pagead2.googlesyndication.com
      https://stats.g.doubleclick.net
      https://*.gstatic.com
      https://*.googleapis.com
      https://*.doubleclick.net
      https://www.recaptcha.net
      https://tagassistant.google.com;
    frame-src
      https://www.google.com
      https://www.google.pl
      https://www.youtube.com
      https://www.recaptcha.net
      https://www.googletagmanager.com;
    style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
    font-src https://fonts.gstatic.com;
    object-src 'none';
    base-uri 'self';
    form-action 'self';
    frame-ancestors 'self';
  """